name: 'openpilot env setup'

inputs:
  save-cache:
    default: false
    required: false

runs:
  using: "composite"
  steps:
    # do this after checkout to ensure our custom LFS config is used to pull from GitLab
    - shell: bash
      run: git lfs pull

    # build cache
    - id: date
      shell: bash
      run: echo "CACHE_COMMIT_DATE=$(git log -1 --pretty='format:%cd' --date=format:'%Y-%m-%d-%H:%M')" >> $GITHUB_ENV
    - shell: bash
      run: echo "$CACHE_COMMIT_DATE"
    - shell: bash
      run: echo "CACHE_SKIP_SAVE=true" >> $GITHUB_ENV
      if: github.ref != 'refs/heads/master' || inputs.save-cache == 'false'
    - id: scons-cache
      uses: buildjet/cache@v3
      with:
        path: ~/scons_cache
        key: scons-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
        restore-keys: |
          scons-${{ env.CACHE_COMMIT_DATE }}-
          scons-

    # build our docker image
    - shell: bash
      run: eval ${{ env.BUILD }}
