name: stale
on:
  schedule:
    - cron: '30 1 * * *'
  push:

env:
  DAYS_BEFORE_CLOSE: 7
  DAYS_BEFORE_STALE: 30

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-pr-message: 'This PR has had no activity for ${{ env.DAYS_BEFORE_STALE }} days. It will be automatically closed in ${{ env.DAYS_BEFORE_CLOSE }} days.'
          delete-branch: ${{ github.event.pull_request.head.repo.full_name != 'commaai/openpilot' }} # only delete branches on the main repo 
          debug-only: true
          exempt-milestones: true
          exempt-pr-labels: "Work In Progress"
          days-before-stale: ${{ env.DAYS_BEFORE_STALE }}
          days-before-close: ${{ env.DAYS_BEFORE_CLOSE }}

